subscribers:

  camera_reading:
    topic: /zed/zed_node/left/image_rect_color
    queue_size: 5

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 5
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 5
    latch: true

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 5
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 3
  enable_console_output: true
