image_view:

  enable_opencv: true
  wait_key_delay: 3
  enable_console_output: true

yolo_model:

  config_file:
    name: yolov3_sidewalk.cfg
  weight_file:
    name: yolov3_sidewalk.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      -barricade
      -bench
      -bicycle
      -bollard
      -bus
      -car
      -carrier
      -cat
      -chair
      -dog
      -fire_hydrant
      -kiosk
      -motorcycle
      -movable_signage
      -parking_meter
      -person
      -pole
      -potted_plant
      -power_controller
      -scooter
      -stop
      -stroller
      -table
      -traffic_light
      -traffic_light_controller
      -traffic_sign
      -tree_trunk
      -truck
      -wheelchair
